import SQLConnection.ConnectionProvider;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import com.toedter.calendar.JDateChooser;
import java.awt.Font;
import java.io.File;
import javax.swing.JFrame;

public class AddAttendance extends javax.swing.JFrame {
    
  public AddAttendance() {
        initComponents();
        Load_Date();
        Load_Stuname();
        Load_Subject();
        Load_Status();
        
          try {
            File fontStyle = new File("src/ttf/RobofanFree.otf");
            Font font = Font.createFont(Font.TRUETYPE_FONT, fontStyle).deriveFont(16f);
            jButton3.setFont(font);
            jButton9.setFont(font);
            jButton7.setFont(font);
            jButton10.setFont(font);
            jButton1.setFont(font);
            jButton8.setFont(font);
            jButton5.setFont(font);
            jButton6.setFont(font);
            jButton4.setFont(font);
            btnClear.setFont(font);
            
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    PreparedStatement pst;
    ResultSet rs;
 
     public void Load_Date() {
         Connection con=ConnectionProvider.getCon();
    try {
        pst = con.prepareStatement("select Distinct datee from date");
        rs = pst.executeQuery();
        CboDate.removeAllItems();

        while (rs.next()) {
            CboDate.addItem(rs.getString("datee"));
        }

    } catch (SQLException ex) {
        ex.printStackTrace();
    } finally {
        try {
            if (rs != null) rs.close();
            if (pst != null) pst.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
}

     public void Load_Stuname() {
         Connection con=ConnectionProvider.getCon();
    try {
        pst = con.prepareStatement("select Distinct stunamee from stuname");
        rs = pst.executeQuery();
        CboStuName.removeAllItems();

        while (rs.next()) {
            CboStuName.addItem(rs.getString("stunamee"));
        }

    } catch (SQLException ex) {
        ex.printStackTrace();
    } finally {
        try {
            if (rs != null) rs.close();
            if (pst != null) pst.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
}

   public void Load_Subject() {
         Connection con=ConnectionProvider.getCon();
    try {
        pst = con.prepareStatement("select Distinct subject from subjects");
        rs = pst.executeQuery();
        CboSubject.removeAllItems();

        while (rs.next()) {
            CboSubject.addItem(rs.getString("subject"));
        }

    } catch (SQLException ex) {
        ex.printStackTrace();
    } finally {
        try {
            if (rs != null) rs.close();
            if (pst != null) pst.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
}
    public void Load_Status() {
         Connection con=ConnectionProvider.getCon();
    try {
        pst = con.prepareStatement("select Distinct statuss from status");
        rs = pst.executeQuery();
        cboStatus.removeAllItems();

        while (rs.next()) {
            cboStatus.addItem(rs.getString("statuss"));
        }

    } catch (SQLException ex) {
        ex.printStackTrace();
    } finally {
        try {
            if (rs != null) rs.close();
            if (pst != null) pst.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Cbodays = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTime = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        CboStuName = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        CboSubject = new javax.swing.JComboBox<>();
        cboStatus = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        CboDate = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtStudentName = new javax.swing.JTextField();
        Date_Chooser1 = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        cbStatus = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtSubject = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtStatus = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtStuname = new javax.swing.JTextField();
        txtsubject = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Cbodays.setBackground(new java.awt.Color(255, 204, 204));
        Cbodays.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Cbodays.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday" }));
        getContentPane().add(Cbodays, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 150, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Days");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Time");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, -1, -1));

        txtTime.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, 150, 36));

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/save.png"))); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 510, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("StuName");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));

        CboStuName.setBackground(new java.awt.Color(255, 204, 204));
        CboStuName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CboStuName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CboStuNameActionPerformed(evt);
            }
        });
        getContentPane().add(CboStuName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 362, 140, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Subject");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, -1, -1));

        CboSubject.setBackground(new java.awt.Color(255, 204, 204));
        CboSubject.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(CboSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, 150, 30));

        cboStatus.setBackground(new java.awt.Color(255, 204, 204));
        cboStatus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(cboStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 150, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Status");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, -1, -1));

        CboDate.setBackground(new java.awt.Color(255, 204, 204));
        CboDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CboDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CboDateActionPerformed(evt);
            }
        });
        getContentPane().add(CboDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 140, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Date");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("StuName");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, -1, -1));

        txtStudentName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtStudentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtStudentName, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 150, -1));

        Date_Chooser1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(Date_Chooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 150, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Date");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, -1, -1));

        jButton3.setBackground(new java.awt.Color(255, 204, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        jButton3.setText("ADD");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, -1, -1));

        jButton7.setBackground(new java.awt.Color(255, 204, 204));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        jButton7.setText("ADD");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, -1, -1));

        jButton10.setBackground(new java.awt.Color(255, 204, 204));
        jButton10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        jButton10.setText("ADD");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 180, -1, -1));

        cbStatus.setBackground(new java.awt.Color(255, 204, 204));
        cbStatus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Present", "Excused Absence", "Absent" }));
        getContentPane().add(cbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 190, 170, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Status");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 190, -1, -1));

        jButton9.setBackground(new java.awt.Color(255, 204, 204));
        jButton9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        jButton9.setText("ADD");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 110, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Subject");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 110, -1, -1));

        txtSubject.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubjectActionPerformed(evt);
            }
        });
        getContentPane().add(txtSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 110, 170, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("-");
        jLabel18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 20, -1, 40));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("X");
        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 30, -1, -1));
        getContentPane().add(txtStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 500, 150, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Add Attendance");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, -1, -1));

        txtStuname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStunameActionPerformed(evt);
            }
        });
        getContentPane().add(txtStuname, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 360, 150, 30));

        txtsubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsubjectActionPerformed(evt);
            }
        });
        getContentPane().add(txtsubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 420, 150, 30));

        jButton5.setBackground(new java.awt.Color(255, 204, 204));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete.png"))); // NOI18N
        jButton5.setText("Delete Stuname");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 360, 190, -1));

        jButton6.setBackground(new java.awt.Color(255, 204, 204));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete.png"))); // NOI18N
        jButton6.setText("Delete Subject");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 420, 190, -1));

        btnClear.setBackground(new java.awt.Color(255, 204, 204));
        btnClear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/clear.png"))); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 570, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Add Attendance Details");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, -1, -1));

        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });
        getContentPane().add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 300, 150, 30));

        jButton8.setBackground(new java.awt.Color(255, 204, 204));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete.png"))); // NOI18N
        jButton8.setText("Delete Date");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 300, 190, -1));

        jButton4.setBackground(new java.awt.Color(255, 204, 204));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete.png"))); // NOI18N
        jButton4.setText("Delete Status");
        jButton4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jButton4StateChanged(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 500, 190, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/neon-city-night.jpg"))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 690));

        setSize(new java.awt.Dimension(1230, 680));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CboStuNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboStuNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CboStuNameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          Connection con=ConnectionProvider.getCon();
        try {
            String date1 = (String)CboDate.getSelectedItem();
            String studentname = (String)CboStuName.getSelectedItem();
            String subject = (String)CboSubject.getSelectedItem();
            String status1 = (String)cboStatus.getSelectedItem();
            String days = (String)Cbodays.getSelectedItem();
            String time = txtTime.getText();

            pst = con.prepareStatement("INSERT INTO attendance(date,stuname,subjects,status,days,time) VALUES (?,?,?,?,?,?)");
            pst.setString(1, date1);
            pst.setString(2, studentname);
            pst.setString(3, subject);
            pst.setString(4, status1);
            pst.setString(5, days);
            pst.setString(6, time);

            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Timetable Registration Successful");

            CboDate.setSelectedIndex(-1);
            CboStuName.setSelectedIndex(-1);
            CboSubject.setSelectedIndex(-1);
            cboStatus.setSelectedIndex(-1);
            Cbodays.setSelectedIndex(-1);
            txtTime.setText("");

        } catch (SQLException ex) {
            Logger.getLogger(TimeReg.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Connection con=ConnectionProvider.getCon();
        try {
        String stunamee = txtStuname.getText();

        pst = con.prepareStatement("DELETE FROM stuname WHERE stunamee=?");
        pst.setString(1, stunamee);

        int deletedRows = pst.executeUpdate();
        if (deletedRows > 0) {
            JOptionPane.showMessageDialog(this, "Record Deleted Successfully");
            Load_Stuname(); // Reload class list after deletion
        } else {
            JOptionPane.showMessageDialog(this, "No record found for the given Student Name.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    } catch (SQLException ex) {
        Logger.getLogger(AddAttendance.class.getName()).log(Level.SEVERE, null, ex);
    }
          txtStuname.setText("");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       Connection con=ConnectionProvider.getCon();
        try {
        String subject = txtsubject.getText();

        pst = con.prepareStatement("DELETE FROM subjects WHERE subject=?");
        pst.setString(1, subject);

        int deletedRows = pst.executeUpdate();
        if (deletedRows > 0) {
            JOptionPane.showMessageDialog(this, "Record Deleted Successfully");
            Load_Subject(); // Reload subject list after deletion
        } else {
            JOptionPane.showMessageDialog(this, "No record found for the given Subject Name.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    } catch (SQLException ex) {
        Logger.getLogger(AddAttendance.class.getName()).log(Level.SEVERE, null, ex);
    }
         txtsubject.setText("");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txtStudentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentNameActionPerformed

    private void txtSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubjectActionPerformed

    private void txtsubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsubjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsubjectActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtDate.setText("");
        txtStuname.setText("");
        txtsubject.setText("");
        txtStatus.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
  Connection con=ConnectionProvider.getCon();
        try {
                    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String date1 = sdf.format(Date_Chooser1.getDate());

            pst = con.prepareStatement("INSERT INTO date(datee) VALUES(?)");
            pst.setString(1, date1);

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Date Registration Successfully");
            Date_Chooser1.setDate(null);
            Load_Date();
        } catch (SQLException ex) {
            Logger.getLogger(AddAttendance.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void CboDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CboDateActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
         Connection con=ConnectionProvider.getCon();
        try {
        String datee = txtDate.getText();

        pst = con.prepareStatement("DELETE FROM date WHERE datee=?");
        pst.setString(1, datee);

        int deletedRows = pst.executeUpdate();
        if (deletedRows > 0) {
            JOptionPane.showMessageDialog(this, "Record Deleted Successfully");
            Load_Date(); // Reload class list after deletion
        } else {
            JOptionPane.showMessageDialog(this, "No record found for the given Date.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    } catch (SQLException ex) {
        Logger.getLogger(AddAttendance.class.getName()).log(Level.SEVERE, null, ex);
    }
          txtDate.setText("");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jButton4StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4StateChanged

    private void txtStunameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStunameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStunameActionPerformed

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      Connection con=ConnectionProvider.getCon();
        try {
        String statuss = txtStatus.getText();

        pst = con.prepareStatement("DELETE FROM status WHERE statuss=?");
        pst.setString(1, statuss);

        int deletedRows = pst.executeUpdate();
        if (deletedRows > 0) {
            JOptionPane.showMessageDialog(this, "Record Deleted Successfully");
            Load_Status(); // Reload class list after deletion
        } else {
            JOptionPane.showMessageDialog(this, "No record found for the given Status Name.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    } catch (SQLException ex) {
        Logger.getLogger(AddAttendance.class.getName()).log(Level.SEVERE, null, ex);
    }
          txtStatus.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
             Connection con=ConnectionProvider.getCon();
        try {
            String studentname = txtStudentName.getText();

            pst = con.prepareStatement("INSERT INTO stuname(stunamee) VALUES(?)");
            pst.setString(1, studentname);

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Student Name Registration Successfully");
            txtStudentName.setText("");
            Load_Stuname();
        } catch (SQLException ex) {
            Logger.getLogger(AddAttendance.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
               Connection con=ConnectionProvider.getCon();
        try {
            String subj = txtSubject.getText();

            pst = con.prepareStatement("INSERT INTO subjects(subject) VALUES(?)");
            pst.setString(1, subj);

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Subject Name Registration Successfully");
            txtSubject.setText("");
            Load_Subject();
        } catch (SQLException ex) {
            Logger.getLogger(AddAttendance.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
                     Connection con=ConnectionProvider.getCon();
        try {
            String status1 = (String) cbStatus.getSelectedItem();

            pst = con.prepareStatement("INSERT INTO status(statuss) VALUES(?)");
            pst.setString(1, status1);

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Present Registration Successfully");
            cbStatus.setSelectedIndex(0);
            Load_Status();
        } catch (SQLException ex) {
            Logger.getLogger(AddAttendance.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel19MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TimeReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TimeReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TimeReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TimeReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddAttendance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CboDate;
    private javax.swing.JComboBox<String> CboStuName;
    private javax.swing.JComboBox<String> CboSubject;
    private javax.swing.JComboBox<String> Cbodays;
    private com.toedter.calendar.JDateChooser Date_Chooser1;
    private javax.swing.JButton btnClear;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JComboBox<String> cboStatus;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtStudentName;
    private javax.swing.JTextField txtStuname;
    private javax.swing.JTextField txtSubject;
    private javax.swing.JTextField txtTime;
    private javax.swing.JTextField txtsubject;
    // End of variables declaration//GEN-END:variables
}
